config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  # devise_for :users
  root to: "pages#home"
  get '/profile', to: 'users#show', as: :user_profile
  get 'gardens/search', to: 'gardens#search', as: 'search_gardens'
  # get 'users/:id' => 'users#show'

  resources :events, only: [:index, :show] do
    resources :bookings, only: [:show, :create, :destroy]
    resources :reviews, only: [:destroy, :create]
    resources :bookmarks, only: [:create, :destroy]
  end

  resources :bookmarks, only: [:create, :destroy]



  resources :gardens do
    resources :events, only: [:index, :new, :create]
    resources :reviews, only: [:destroy, :create]
    resources :parcels, only: [:new, :create, :index, :show]

  end


  resources :parcels do
    resources :parcel_reservations, only: [:new, :create, :update]
  end


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/parcel.rb
class Parcel < ApplicationRecord
  belongs_to :garden
  has_many :parcel_reservations, dependent: :destroy
  has_one_attached :photo
  # validates :
end

app/controllers/parcels_controller.rb
class ParcelsController < ApplicationController
  before_action :check_admin, only: [:new, :create, :index]
  before_action :set_garden, only: [:new, :create]

  def index
    @parcels = Parcel.all
  end

  def new
    @garden = Garden.find(params[:garden_id])
    @parcel = Parcel.new
    @parcel_reservation = ParcelReservation.new
  end


  def create
    @parcel = @garden.parcels.new(parcel_params)
    if @parcel.save
      redirect_to garden_path(@parcel.garden), notice: 'Parcel was successfully created.'
    else
      render :new
    end
  end

  def show
    @parcel = Parcel.find(params[:id])
  end

  private

  def set_garden
    @garden = Garden.find(params[:garden_id])
  end

  def parcel_params
    params.require(:parcel).permit(:garden_id, :name, :size, :photo)
  end

  def check_admin
    redirect_to root_path, alert: "Not authorized" unless current_user.is_admin?
  end
end

app/views/parcels/_parcel.html.erb
<% @parcels.each do |parcel| %>
  <%= render "parcels/shared/parcel", parcel: parcel %>
<% end %>

app/views/parcels/index.html.erb
<div class="parcel-container">
  <h1>Parcels</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Size</th>
        <th>Garden</th>
        <th>Reservations</th>
      </tr>
    </thead>
    <tbody>
      <% @parcels.each do |parcel| %>
        <tr>
          <td><%= parcel.name %></td>
          <td><%= parcel.size %></td>
          <td><%= parcel.garden.name %></td>
          <td>
            <% parcel.parcel_reservations.each do |reservation| %>
              <div class="reservation-item">
                <p><strong>User:</strong> <%= reservation.user.name %>, <strong>Status:</strong> <%= reservation.status %></p>
                <%= form_with model: reservation, url: parcel_reservation_path(reservation), method: :patch, class: 'reservation-form' do |form| %>
                  <%= form.select :status, ['accepted', 'rejected'], include_blank: true %>
                  <%= form.submit "Update" %>
                <% end %>
              </div>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/parcels/new.html.erb
<div class="container scrollable-container">
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="event-card-index2">
        <div class="img-container">
          <% if @garden.photos.attached? %>
            <%= link_to garden_path(@garden) do %>
              <%= cl_image_tag @garden.photos.first.key, alt: @garden.name, class: 'img-fluid rounded d-block w-100' %>
            <% end %>
          <% else %>
            <%= link_to garden_path(@garden) do %>
              <%= image_tag "logo.png", alt: "default image", class: 'img-fluid rounded d-block w-100' %>
            <% end %>
          <% end %>
        </div>
        <h2><%= @garden.name %></h2>
        <div class="events-atribute-list">
          <span class="event-atribute">
            <div class="svg-icons-events-attribute">
              <svg xmlns="http://www.w3.org/2000/svg" fill="#000000" width="800px" height="800px" viewBox="0 0 32 32" version="1.1">
                <path d="M16.114-0.011c-6.559 0-12.114 5.587-12.114 12.204 0 6.93 6.439 14.017 10.77 18.998 0.017 0.020 0.717 0.797 1.579 0.797h0.076c0.863 0 1.558-0.777 1.575-0.797 4.064-4.672 10-12.377 10-18.998 0-6.618-4.333-12.204-11.886-12.204zM16.515 29.849c-0.035 0.035-0.086 0.074-0.131 0.107-0.046-0.032-0.096-0.072-0.133-0.107l-0.523-0.602c-4.106-4.71-9.729-11.161-9.729-17.055 0-5.532 4.632-10.205 10.114-10.205 6.829 0 9.886 5.125 9.886 10.205 0 4.474-3.192 10.416-9.485 17.657zM16.035 6.044c-3.313 0-6 2.686-6 6s2.687 6 6 6 6-2.687 6-6-2.686-6-6-6zM16.035 16.044c-2.206 0-4.046-1.838-4.046-4.044s1.794-4 4-4c2.207 0 4 1.794 4 4 0.001 2.206-1.747 4.044-3.954 4.044z"/>
              </svg>
            </div>
            <%= @garden.location %>
          </span>
          <span class="event-atribute">
          </span>
        </div>
        <div class="card-description">
          <p><%= @garden.description.split(/(?<=\.)\s+|$/).first %></p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="event-card-index2">
        <%= simple_form_for [@garden, @parcel], url: garden_parcels_path(@garden) do |f| %>
          <%= f.input :name, class: 'form-control' %>
          <%= f.input :size, class: 'form-control' %>
          <%= f.input :photo, as: :file, class: 'form-control-file' %>
          <%= f.button :submit, class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>
```

app/views/parcels/show.html.erb
<%= link_to 'Reserve Parcel', new_garden_parcel_parcel_reservation_path(garden_id: @garden.id, parcel_id: @parcel.id) %>