config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  # devise_for :users
  root to: "pages#home"
  get '/profile', to: 'users#show', as: :user_profile
  get 'gardens/search', to: 'gardens#search', as: 'search_gardens'
  # get 'users/:id' => 'users#show'

  resources :events, only: [:index, :show] do
    resources :bookings, only: [:show, :create, :destroy]
    resources :reviews, only: [:destroy, :create]
    resources :bookmarks, only: [:create, :destroy]
  end

  resources :bookmarks, only: [:create, :destroy]



  resources :gardens do
    resources :events, only: [:index, :new, :create]
    resources :reviews, only: [:destroy, :create]
    resources :parcels, only: [:new, :create, :index, :show]

  end


  resources :parcels do
    resources :parcel_reservations, only: [:new, :create, :update]
  end


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :gardens, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :events, through: :gardens
  has_many :parcels
  has_many :parcel_reservations
  has_many :reserved_parcels, through: :parcel_reservations, source: :parcel
  has_many :reviews, dependent: :destroy

  has_many :attending_events, through: :bookings, source: :event

  # has_many :events, through: :gardens
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_one_attached :photo

  validates :first_name, :last_name, presence: true
  validates :bio, presence: false
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    @user = User.new(sign_up_params)
    image1_path = Rails.root.join('lib', 'assets', 'seeds', 'images', 'Avatar1.png')
    image1 = File.open(image1_path)
    @user.photo.attach(io: image1, filename: 'Avatar1.png', content_type: 'image/png')
    if @user.save
      redirect_to user_profile_path(@user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private

  def sign_up_params
    devise_parameter_sanitizer.sanitize(:sign_up)
  end

  def user_params
    params.require(:user).permit(%i[first_name last_name email password password_confirmation])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if params[:id]
      @user = User.find(params[:id])
    else
      @user = current_user
    end


    @gardens = @user.gardens
    @favourited_gardens = @user.bookmarks
    @favourites = @user.bookmarks
    @attending_events = @user.attending_events
    @events = @user.events
    @parcels = Parcel.where(garden_id: @gardens.pluck(:id))
    @parcel_reservations = @user.parcel_reservations.includes(:parcel)
  end

end

app/views/users/show.html.erb
<div class='profile-top-section'>
  <div class="profile-banner">
  <%= video_tag('animatedprofile.mp4', id: 'profile-background', autoplay: true, loop: true, muted: true) %>
</div>

<div class="user-info">
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, class: "user-image-container" %>
        <% else %>
          <div class="user-image-container"></div>
        <% end %>
      <div class="user-name-container">
        <p class="user-fname"><%= @user.first_name %></p>
        <p class="user-lname"><%= @user.last_name %></p>
      </div>
      <% if current_user.is_admin %>
        <p class="user-type">Garden administrator</p>
      <% else %>
        <p class="user-type">Plant enthusiast</p>
      <% end %>
    </div>
</div>

<div class="container">
  <div class="profile-card">

    <div class="user-info-bottom">
      <div class="accordion" id="accordionExample">


        <%# My gardens (admin only) %>
        <% if current_user.is_admin %>
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingThree">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                  My gardens
                </button>
            </h2>
            <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
              <div class="accordion-body">
                <% if @gardens.any? %>
                  <div class="event-list">
                    <div class="event-container">
                      <% @gardens.each do |garden| %>
                        <%= render "gardens/garden_card", garden: garden%>
                      <% end %>
                    </div>
                  </div>
                <% else %>
                  <p class="no-events">You have no gardens yet...</p>
                <% end %>
              </div>
            </div>
          </div>

        <%# My Events  %>
        <div class="accordion-item">
          <h2 class="accordion-header" id="myEventsAccordion">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#myEventsContent" aria-expanded="false" aria-controls="myEventsContent">
              My events
            </button>
          </h2>
          <div id="myEventsContent" class="accordion-collapse collapse" aria-labelledby="myEventsAccordion" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              <div class="event-list">
                <div class="events">
                  <% if @events.any? %>
                    <% @events.each do |event| %>
                      <%= render "events/event_card", event: event %>
                    <% end %>
                  <% else %>
                    <p class="no-events">You have no events yet...</p>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>

        <% end %>
        <%# Events Im attending %>
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
              Events I'm attending
            </button>
          </h2>
          <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              <% if @attending_events.any? %>
                <%= render "shared/event", events: @attending_events %>
              <% else %>
                <p class="no-events">You have no events scheduled...</p>
              <% end %>
            </div>
          </div>
        </div>

                <%# Favourite gardens%>
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingTwo">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              Favourite Gardens
            </button>
          </h2>
          <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              <% if @favourited_gardens.any? %>
                  <div class="event-list">
                      <% @favourited_gardens.each do |bookmark| %>
                        <%= render "gardens/garden_card", garden: bookmark.garden%>
                      <% end %>
                  </div>
                <% else %>
                  <p class="no-events">You have no favourite gardens...</p>
                <% end %>
            </div>
          </div>
        </div>


        <div class="accordion-item">
          <h2 class="accordion-header" id="headingFour">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
              <% if current_user.is_admin  %>
                My Parcels
              <% else %>
                My reserved parcels
              <% end %>
            </button>
          </h2>
          <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              <% if current_user.is_admin %>
                <% if @parcels.any? %>
                  <ul class="list-group">
                    <% @parcels.each do |parcel| %>
                      <li class="list-group-item"><%= parcel.name %></li>
                    <% end %>
                  </ul>
                <% else %>
                  <p class="no-events">You have no parcels...</p>
                <% end %>
              <% else %>
                <%= render "parcel_reservations/list", parcel_reservations: @parcel_reservations %>
              <% end %>
            </div>
          </div>
        </div>

      </div>
    </div>
    <% if @gardens.present? && current_user.is_admin %>

  <%= link_to 'Add garden', new_garden_path, class: "action-button" %>

  <%= link_to "Add event", new_garden_event_path(garden_id: @gardens.first.id), class: "action-button" %>
  <%= link_to "Add parcel", new_garden_parcel_path(garden_id: @gardens.first.id), class: "action-button" %>
  <% elsif current_user.is_admin %>
  <%= link_to "Add a new garden", new_garden_path, class: "action-button" %>
  <p>No gardens available to add events.</p>
<% end %>
  <%= button_to "Log out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: 'inset-action-button last-button', form_class: "profile-logout"%>
  </div>
</div>