config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  # devise_for :users
  root to: "pages#home"
  get '/profile', to: 'users#show', as: :user_profile
  get 'gardens/search', to: 'gardens#search', as: 'search_gardens'
  # get 'users/:id' => 'users#show'

  resources :events, only: [:index, :show] do
    resources :bookings, only: [:show, :create, :destroy]
    resources :reviews, only: [:destroy, :create]
    resources :bookmarks, only: [:create, :destroy]
  end

  resources :bookmarks, only: [:create, :destroy]



  resources :gardens do
    resources :events, only: [:index, :new, :create]
    resources :reviews, only: [:destroy, :create]
    resources :parcels, only: [:new, :create, :index, :show]

  end


  resources :parcels do
    resources :parcel_reservations, only: [:new, :create, :update]
  end


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_action_button.html.erb
<button class="action-button">Book</button>

app/views/shared/_event.html.erb
    <% events.each do |event| %>
      <div class="event-card-index">
        <div class="img-container">
          <%= cl_image_tag event.photo.key, class:"d-block w-100" %>
          <% if params[:controller] == "users"%>
            <h2 style="width:100%;"><%= event.name %></h2>
          <% else %>
            <h2 id="attending-h2"><%= event.name %></h2>
          <% end %>
        </div>

        <% if event.garden %>
          <div class="events-atribute-list">
            <span class="event-atribute">
          <div class="svg-icons-events-attribute">
              <svg xmlns="http://www.w3.org/2000/svg" fill="#000000" width="800px" height="800px" viewBox="0 0 32 32" version="1.1">
              <path d="M16.114-0.011c-6.559 0-12.114 5.587-12.114 12.204 0 6.93 6.439 14.017 10.77 18.998 0.017 0.020 0.717 0.797 1.579 0.797h0.076c0.863 0 1.558-0.777 1.575-0.797 4.064-4.672 10-12.377 10-18.998 0-6.618-4.333-12.204-11.886-12.204zM16.515 29.849c-0.035 0.035-0.086 0.074-0.131 0.107-0.046-0.032-0.096-0.072-0.133-0.107l-0.523-0.602c-4.106-4.71-9.729-11.161-9.729-17.055 0-5.532 4.632-10.205 10.114-10.205 6.829 0 9.886 5.125 9.886 10.205 0 4.474-3.192 10.416-9.485 17.657zM16.035 6.044c-3.313 0-6 2.686-6 6s2.687 6 6 6 6-2.687 6-6-2.686-6-6-6zM16.035 16.044c-2.206 0-4.046-1.838-4.046-4.044s1.794-4 4-4c2.207 0 4 1.794 4 4 0.001 2.206-1.747 4.044-3.954 4.044z"/>
            </svg>
          </div>
          <%= event.garden.name %>
        </span>
        <% end %>
        <span class="event-atribute">
        <div class="svg-icons-events-attribute">
          <svg xmlns="http://www.w3.org/2000/svg" width="800px" height="800px" viewBox="0 0 24 24" fill="none">
              <rect width="24" height="24" fill="white"/>
              <g filter="url(#filter0_d_15_268)">
              <path d="M3 8.26667V19C3 19.5523 3.44772 20 4 20H20C20.5523 20 21 19.5523 21 19V8.26667M3 8.26667V5C3 4.44772 3.44772 4 4 4H20C20.5523 4 21 4.44772 21 5V8.26667M3 8.26667H21" stroke="#000000" stroke-linejoin="round"/>
              </g>
              <g filter="url(#filter1_d_15_268)">
              <path d="M7 2V5" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"/>
              </g>
              <g filter="url(#filter2_d_15_268)">
              <path d="M17 2V5" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"/>
              </g>
              <g filter="url(#filter3_d_15_268)">
              <path d="M18 11H16" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"/>
              </g>
              <g filter="url(#filter4_d_15_268)">
              <path d="M18 17H16" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"/>
              </g>
              <g filter="url(#filter5_d_15_268)">
              <path d="M13 11H11" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"/>
              </g>
              <g filter="url(#filter6_d_15_268)">
              <path d="M13 17H11" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"/>
              </g>
              <g filter="url(#filter7_d_15_268)">
              <path d="M8 11H6" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"/>
              </g>
              <g filter="url(#filter8_d_15_268)">
              <path d="M8 17H6" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"/>
              </g>
              <g filter="url(#filter9_d_15_268)">
              <path d="M18 14H16" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"/>
              </g>
              <g filter="url(#filter10_d_15_268)">
              <path d="M13 14H11" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"/>
              </g>
              <g filter="url(#filter11_d_15_268)">
              <path d="M8 14H6" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"/>
              </g>
              <defs>
              <filter id="filter0_d_15_268" x="1.5" y="3.5" width="21" height="19" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
              <feFlood flood-opacity="0" result="BackgroundImageFix"/>
              <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
              <feOffset dy="1"/>
              <feGaussianBlur stdDeviation="0.5"/>
              <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.1 0"/>
              <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_15_268"/>
              <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_15_268" result="shape"/>
              </filter>
              <filter id="filter1_d_15_268" x="5.5" y="1.5" width="3" height="6" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
              <feFlood flood-opacity="0" result="BackgroundImageFix"/>
              <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
              <feOffset dy="1"/>
              <feGaussianBlur stdDeviation="0.5"/>
              <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.1 0"/>
              <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_15_268"/>
              <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_15_268" result="shape"/>
              </filter>
              <filter id="filter2_d_15_268" x="15.5" y="1.5" width="3" height="6" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
              <feFlood flood-opacity="0" result="BackgroundImageFix"/>
              <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
              <feOffset dy="1"/>
              <feGaussianBlur stdDeviation="0.5"/>
              <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.1 0"/>
              <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_15_268"/>
              <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_15_268" result="shape"/>
              </filter>
              <filter id="filter3_d_15_268" x="14.5" y="10.5" width="5" height="3" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
              <feFlood flood-opacity="0" result="BackgroundImageFix"/>
              <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
              <feOffset dy="1"/>
              <feGaussianBlur stdDeviation="0.5"/>
              <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.1 0"/>
              <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_15_268"/>
              <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_15_268" result="shape"/>
              </filter>
              <filter id="filter4_d_15_268" x="14.5" y="16.5" width="5" height="3" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
              <feFlood flood-opacity="0" result="BackgroundImageFix"/>
              <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
              <feOffset dy="1"/>
              <feGaussianBlur stdDeviation="0.5"/>
              <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.1 0"/>
              <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_15_268"/>
              <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_15_268" result="shape"/>
              </filter>
              <filter id="filter5_d_15_268" x="9.5" y="10.5" width="5" height="3" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
              <feFlood flood-opacity="0" result="BackgroundImageFix"/>
              <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
              <feOffset dy="1"/>
              <feGaussianBlur stdDeviation="0.5"/>
              <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.1 0"/>
              <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_15_268"/>
              <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_15_268" result="shape"/>
              </filter>
              <filter id="filter6_d_15_268" x="9.5" y="16.5" width="5" height="3" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
              <feFlood flood-opacity="0" result="BackgroundImageFix"/>
              <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
              <feOffset dy="1"/>
              <feGaussianBlur stdDeviation="0.5"/>
              <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.1 0"/>
              <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_15_268"/>
              <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_15_268" result="shape"/>
              </filter>
              <filter id="filter7_d_15_268" x="4.5" y="10.5" width="5" height="3" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
              <feFlood flood-opacity="0" result="BackgroundImageFix"/>
              <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
              <feOffset dy="1"/>
              <feGaussianBlur stdDeviation="0.5"/>
              <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.1 0"/>
              <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_15_268"/>
              <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_15_268" result="shape"/>
              </filter>
              <filter id="filter8_d_15_268" x="4.5" y="16.5" width="5" height="3" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
              <feFlood flood-opacity="0" result="BackgroundImageFix"/>
              <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
              <feOffset dy="1"/>
              <feGaussianBlur stdDeviation="0.5"/>
              <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.1 0"/>
              <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_15_268"/>
              <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_15_268" result="shape"/>
              </filter>
              <filter id="filter9_d_15_268" x="14.5" y="13.5" width="5" height="3" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
              <feFlood flood-opacity="0" result="BackgroundImageFix"/>
              <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
              <feOffset dy="1"/>
              <feGaussianBlur stdDeviation="0.5"/>
              <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.1 0"/>
              <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_15_268"/>
              <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_15_268" result="shape"/>
              </filter>
              <filter id="filter10_d_15_268" x="9.5" y="13.5" width="5" height="3" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
              <feFlood flood-opacity="0" result="BackgroundImageFix"/>
              <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
              <feOffset dy="1"/>
              <feGaussianBlur stdDeviation="0.5"/>
              <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.1 0"/>
              <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_15_268"/>
              <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_15_268" result="shape"/>
              </filter>
              <filter id="filter11_d_15_268" x="4.5" y="13.5" width="5" height="3" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
              <feFlood flood-opacity="0" result="BackgroundImageFix"/>
              <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
              <feOffset dy="1"/>
              <feGaussianBlur stdDeviation="0.5"/>
              <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.1 0"/>
              <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_15_268"/>
              <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_15_268" result="shape"/>
              </filter>
              </defs>
            </svg>
          </div>
        <%= event.date.strftime('%B %d, %Y') %>
        </span>
          </div>
        <div class="card-description">
          <p><%= truncate(event.description, length: 100) %></p>
        </div>
      </div>
    <% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-centered">

  <div>

  </div>


    <%= image_tag "footer-logo.png", class: "footer-logo" %>
    <p class="footer-text">© 2023 Spaceit EU, all rights reserved</p>
  </div>
</footer>

app/views/shared/_gardens.html.erb
<% if @gardens.any? %>
<div class="event-card-index">
  <div class="img-container">
    <% if garden.photos.attached? %>
      <%= link_to garden_path(garden) do %>
        <%= cl_image_tag garden.photos.first.key, class: "d-block w-100" %>
      <% end %>
    <% else %>
      <%= link_to garden_path(garden) do %>
        <%= image_tag "logo.png", alt: "default image", class: 'd-block w-100' %>
      <% end %>
    <% end %>
    <div class="name-container" style="display: flex; align-items: center; justify-content: space-between; width: 398px;">>
      <h2><%= garden.name %></h2>
        <i class="fa-regular fa-heart" style="color: #ffffff;"></i>
    </div>
  </div>
  <div class="events-atribute-list">
    <span class="event-atribute">
      <div class="svg-icons-events-attribute">
          <svg xmlns="http://www.w3.org/2000/svg" fill="#000000" width="800px" height="800px" viewBox="0 0 32 32" version="1.1">
          <path d="M16.114-0.011c-6.559 0-12.114 5.587-12.114 12.204 0 6.93 6.439 14.017 10.77 18.998 0.017 0.020 0.717 0.797 1.579 0.797h0.076c0.863 0 1.558-0.777 1.575-0.797 4.064-4.672 10-12.377 10-18.998 0-6.618-4.333-12.204-11.886-12.204zM16.515 29.849c-0.035 0.035-0.086 0.074-0.131 0.107-0.046-0.032-0.096-0.072-0.133-0.107l-0.523-0.602c-4.106-4.71-9.729-11.161-9.729-17.055 0-5.532 4.632-10.205 10.114-10.205 6.829 0 9.886 5.125 9.886 10.205 0 4.474-3.192 10.416-9.485 17.657zM16.035 6.044c-3.313 0-6 2.686-6 6s2.687 6 6 6 6-2.687 6-6-2.686-6-6-6zM16.035 16.044c-2.206 0-4.046-1.838-4.046-4.044s1.794-4 4-4c2.207 0 4 1.794 4 4 0.001 2.206-1.747 4.044-3.954 4.044z"/>
        </svg>
      </div>
      <%= garden.name %>
    </span>
    <span class="event-atribute">
      <div class="svg-icons-events-attribute">
          <svg xmlns="http://www.w3.org/2000/svg" fill="#000000" width="800px" height="800px" viewBox="0 0 32 32" version="1.1">
          <path d="M16.114-0.011c-6.559 0-12.114 5.587-12.114 12.204 0 6.93 6.439 14.017 10.77 18.998 0.017 0.020 0.717 0.797 1.579 0.797h0.076c0.863 0 1.558-0.777 1.575-0.797 4.064-4.672 10-12.377 10-18.998 0-6.618-4.333-12.204-11.886-12.204zM16.515 29.849c-0.035 0.035-0.086 0.074-0.131 0.107-0.046-0.032-0.096-0.072-0.133-0.107l-0.523-0.602c-4.106-4.71-9.729-11.161-9.729-17.055 0-5.532 4.632-10.205 10.114-10.205 6.829 0 9.886 5.125 9.886 10.205 0 4.474-3.192 10.416-9.485 17.657zM16.035 6.044c-3.313 0-6 2.686-6 6s2.687 6 6 6 6-2.687 6-6-2.686-6-6-6zM16.035 16.044c-2.206 0-4.046-1.838-4.046-4.044s1.794-4 4-4c2.207 0 4 1.794 4 4 0.001 2.206-1.747 4.044-3.954 4.044z"/>
        </svg>
      </div>
      <%= garden.name %>
    </span>
    <span class="event-atribute">
      <div class="svg-icons-events-attribute">
        <%# <%= render "event_icons" %>
      </div>
    </span>
  </div>
  <div class="card-description">
    <p><%= garden.description.split(/(?<=\.)\s+|$/).first %></p>
  </div>
</div>

<% else %>
  <p>No favourites found.</p>
<% end %>

app/views/shared/_navbar.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Community Garden App</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>

  <div class="page-content">
  </div>

  <div class="bottom-navbar">
    <a href="<%= root_path%>" class="nav-item">
      <i class="fa-solid fa-house" style="color: #fff;"></i>
    </a>
    <a  href="<%= events_path %>" class="nav-item">
      <i class="fa-solid fa-magnifying-glass" style="color: #fff;"></i>
    </a>
    <a href="<%= gardens_path %>" class="nav-item">
      <i class="fa-solid fa-seedling" style="color: #fff;"></i>
    </a>
    <a href="<%= user_profile_path %>" class="nav-item">
      <i class="fa-solid fa-user" style="color: #fff;"></i>
    </a>
  </div>

</body>
</html>