config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  # devise_for :users
  root to: "pages#home"
  get '/profile', to: 'users#show', as: :user_profile
  get 'gardens/search', to: 'gardens#search', as: 'search_gardens'
  # get 'users/:id' => 'users#show'

  resources :events, only: [:index, :show] do
    resources :bookings, only: [:show, :create, :destroy]
    resources :reviews, only: [:destroy, :create]
    resources :bookmarks, only: [:create, :destroy]
  end

  resources :bookmarks, only: [:create, :destroy]



  resources :gardens do
    resources :events, only: [:index, :new, :create]
    resources :reviews, only: [:destroy, :create]
    resources :parcels, only: [:new, :create, :index, :show]

  end


  resources :parcels do
    resources :parcel_reservations, only: [:new, :create, :update]
  end


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/garden.rb
class Garden < ApplicationRecord
  belongs_to :user
  has_many :events, dependent: :destroy
  has_many :parcels, dependent: :destroy
  #has_many :reviews, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: ->(obj) { obj.location.present? }
  has_many_attached :photos
  has_many :bookmarks, dependent: :destroy

  geocoded_by :location
  after_validation :geocode, if: ->(obj) { obj.location.present? }
  has_many_attached :photos

  def available_parcels
    self.parcels.reject { |parcel| parcel.parcel_reservations.any? }.count
  end
  def available_parcel_objects
    self.parcels.reject { |parcel| parcel.parcel_reservations.any? }
  end
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: [:show, :update, :destroy]

  def show
    @garden = Garden.find(params[:id])
    @review = Review.new
    reviews = Review.where(reviewable_type: "Garden")
    @garden_reviews = reviews.where(reviewable_id: @garden.id)
  end

  def index
    if params[:query].present?
        @gardens = search_gardens(params[:query])
    else
        @gardens = Garden.all
    end
  end


  def search_gardens(query)
    sql_subquery = "name ILIKE :query OR description ILIKE :query OR location ILIKE :query"
    Garden.where(sql_subquery, query: "%#{query}%")
  end

  def new
    @garden = Garden.new
  end

  def create
    @garden = Garden.new(garden_params)
    @garden.user = current_user

    if @garden.save
      redirect_to @garden, notice: 'Garden was successfully created.'
    else
      render :new
    end
  end


  def update
    if @garden.update(garden_params)
      redirect_to @garden, notice: 'Garden was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @garden.destroy
    redirect_to gardens_url, notice: 'Garden was successfully destroyed.'
  end

  private

  def set_garden
    @garden = Garden.find(params[:id])
  end


  def garden_params
    params.require(:garden).permit(:name, :location, :description, :latitude, :longitude, photos: [])
  end
end

app/views/gardens/_garden_card.html.erb
<div class="items-list" data-controller="bookmarks">
  <div class="event-card-index">
    <div class="img-container">
      <% if garden.photos.any? %>
        <%= link_to garden_path(garden) do %>
          <%= cl_image_tag garden.photos.first.key, alt: garden.name, class: 'd-block w-100' %>
        <% end %>
      <% else %>
        <%= link_to garden_path(garden) do %>
          <%= image_tag "logo.png", alt: "default image", class: 'd-block w-100' %>
        <% end %>
      <% end %>
      <h2><%= garden.name %></h2>
    </div>

    <div class="events-atribute-list">
      <span class="event-atribute">
        <div class="svg-icons-events-attribute">
            <svg xmlns="http://www.w3.org/2000/svg" fill="#0a0e06" width="800px" height="800px" viewBox="0 0 32 32" version="1.1">
            <path d="M16.114-0.011c-6.559 0-12.114 5.587-12.114 12.204 0 6.93 6.439 14.017 10.77 18.998 0.017 0.020 0.717 0.797 1.579 0.797h0.076c0.863 0 1.558-0.777 1.575-0.797 4.064-4.672 10-12.377 10-18.998 0-6.618-4.333-12.204-11.886-12.204zM16.515 29.849c-0.035 0.035-0.086 0.074-0.131 0.107-0.046-0.032-0.096-0.072-0.133-0.107l-0.523-0.602c-4.106-4.71-9.729-11.161-9.729-17.055 0-5.532 4.632-10.205 10.114-10.205 6.829 0 9.886 5.125 9.886 10.205 0 4.474-3.192 10.416-9.485 17.657zM16.035 6.044c-3.313 0-6 2.686-6 6s2.687 6 6 6 6-2.687 6-6-2.686-6-6-6zM16.035 16.044c-2.206 0-4.046-1.838-4.046-4.044s1.794-4 4-4c2.207 0 4 1.794 4 4 0.001 2.206-1.747 4.044-3.954 4.044z"/>
          </svg>
        </div>
        <%= garden.location%>
      </span>
      <% if current_user && current_user.bookmarks.pluck(:garden_id).include?(garden.id)%>
        <% bookmark = Bookmark.find_by(garden: garden, user: current_user) %>
        <span class="click-favorite">
          <%= link_to '<i class="fa-solid fa-heart" style="color: #0a0e06;"></i>'.html_safe, "#", data: {gardenId: bookmark.id, action: 'click->bookmarks#deleteFavourited'}%>
        </span>
      <% else %>
        <span class="click-favorite">
          <%= link_to '<i class="fa-regular fa-heart" style="color: #0a0e06;"></i>'.html_safe, "#", data: {gardenId: garden.id, action: 'click->bookmarks#favourited'}%>
        </span>
      <% end %>
    </div>
    <div class="card-description">
      <p><%= garden.description.split(/(?<=\.)\s+|$/).first %></p>
    </div>
  </div>
</div>

app/views/gardens/_search_bar.html.erb
<div class="search-container">
  <div class="search-container-inner">
    <%= form_with url: gardens_path, method: :get, class: "search-input-form", remote: true, data: { controller: "search-garden", action: "search#submit" } do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control-search search-query-input-new",
        placeholder: "Type a keyword",
        data: { target: "search.query" }
      %>
      <div class="button-search-form-css">
        <%= submit_tag "", class: "search-input-submit-button" %>
        <span class="svg-icon-search"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" style="display:block;fill:none;height:12px;width:12px;stroke:currentColor;stroke-width:5.333333333333333;overflow:visible" aria-hidden="true" role="presentation" focusable="false"><path fill="none" d="M13 24a11 11 0 1 0 0-22 11 11 0 0 0 0 22zm8-3 9 9"></path></svg></span>
      </div>
    <% end %>
  </div>
</div>

app/views/gardens/index.html.erb
<div class="title-index">
  <div class="title-inner">
    <%= render 'gardens/search_bar' %>
  </div>
  <h1>Gardens in Barcelona</h1>
</div>
<div class="events-dynamic-container">
  <div class="event-list">
    <div class="events-container">
      <% @gardens.each do |garden| %>
        <%= render "garden_card", garden: garden %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/gardens/new.html.erb
<div class="events-add-new">
  <div class="form-container">
    <div class="new-container">
      <div class="new-container-head">
        <h3 class="tirtuary-h">Please fill in the information about the garden</h3>
      </div>
      <%= simple_form_for @garden do |f| %>
        <%= f.input :name, wrapper_html: { class: "f-input" }, label: "Garden title" %>
        <%= f.input :description, wrapper_html: { class: "f-input" } %>
        <%= f.input :location, wrapper_html: { class: "f-input" }, label: "Garden location" %>
        <%= f.input :photos, as: :file, input_html: { multiple: true }, label: "Upload garden photos" %>

        <%= f.input :photo, as: :file, input_html: { multiple: false }, label: "Upload garden photo" %>
        <%= f.button :submit, wrapper_html: { class: "action-button" } %>
      <% end %>
    </div>
  </div>
</div>

app/views/gardens/show.html.erb
<div class="events-show">
  <section class="section-show mx-2">
    <div class="show-container">
      <div class="show-photo-column">
        <% if @garden.photos.attached? %>
          <%= cl_image_tag(@garden.photos.first.key, alt: @garden.name, class: "garden-show-image") %>
        <% else %>
          <%= image_tag('logo.png', alt: 'No image available', class: "garden-show-image") %>
        <% end %>
      </div>

      <div class="show-description-column mx-3 mt-3">
        <h3 class="show-event-title"><strong><%= @garden.name %></strong></h3>
        <p class="event-address"><%= @garden.location %></p>
        <hr>

        <p class="show-description"><%= @garden.description %></p>
        <hr>

        <div class="available-parcels">
          <h4>Available Parcels</h4>
          <% if @garden.available_parcel_objects.any? %>
            <ul>
              <% @garden.available_parcel_objects.each do |parcel| %>
                <li class="parcel-item">
                  <%= image_tag(parcel.image_url, alt: parcel.name, class: "parcel-image") if parcel.image_url.present? %>
                  <%= link_to parcel.name, new_parcel_parcel_reservation_path(parcel_id: parcel.id), class: "parcel-link" %>
                </li>
              <% end %>
            </ul>
          <% else %>
            <p>No parcels available</p>
          <% end %>
        </div>
        <hr>
        <h4>Reviews</h4>

        <div class="reviews-section">
          <% @garden_reviews.each do |review| %>
            <div class="reviews-container">
              <div class="review-date">
                <p> <%= review.created_at.strftime("%d %B %Y %R") %></p>
              </div>
              <div class="d-flex mb-3">
                <% review.rating.times do %>
                  <span class="fa fa-star checked"></span>
                <% end %>
                <% (5 - review.rating).times do %>
                  <span class="fa fa-star unchecked"></span>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>

        <%= simple_form_for [@garden, @review] do |f| %>
          <%= f.input :rating, collection: (1..5), label: 'Rating', input_html: { class: 'custom-rating-input' } %>
          <%= f.input :content, label: 'Review', as: :text, input_html: { class: 'custom-review-textarea' } %>
          <div class="d-flex justify-content-end">
            <%= f.submit "Submit Review", class: "action-button review-button" %>
          </div>
        <% end %>

        <hr>

      </div>
    </div>
  </section>
</div>